=begin
#White Label Communications CPaas API Documentation

#A CPaaS platform API

The version of the OpenAPI document: 1.1
Contact: support@whitelabelcomm.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'date'
require 'time'

module OpenapiClient
  class ServiceParkingSlotData
    attr_accessor :attended

    attr_accessor :call_id

    attr_accessor :cid_name

    attr_accessor :cid_number

    attr_accessor :cid_uri

    attr_accessor :from_tag

    attr_accessor :node

    attr_accessor :presence_id

    attr_accessor :presence_realm

    attr_accessor :presence_type

    attr_accessor :presence_user

    attr_accessor :ringback_id

    attr_accessor :slot_call_id

    attr_accessor :switch_uri

    attr_accessor :to_tag

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'attended' => :'attended',
        :'call_id' => :'call_id',
        :'cid_name' => :'cid_name',
        :'cid_number' => :'cid_number',
        :'cid_uri' => :'cid_uri',
        :'from_tag' => :'from_tag',
        :'node' => :'node',
        :'presence_id' => :'presence_id',
        :'presence_realm' => :'presence_realm',
        :'presence_type' => :'presence_type',
        :'presence_user' => :'presence_user',
        :'ringback_id' => :'ringback_id',
        :'slot_call_id' => :'slot_call_id',
        :'switch_uri' => :'switch_uri',
        :'to_tag' => :'to_tag'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'attended' => :'Boolean',
        :'call_id' => :'String',
        :'cid_name' => :'String',
        :'cid_number' => :'String',
        :'cid_uri' => :'String',
        :'from_tag' => :'String',
        :'node' => :'String',
        :'presence_id' => :'String',
        :'presence_realm' => :'String',
        :'presence_type' => :'String',
        :'presence_user' => :'String',
        :'ringback_id' => :'String',
        :'slot_call_id' => :'String',
        :'switch_uri' => :'String',
        :'to_tag' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::ServiceParkingSlotData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::ServiceParkingSlotData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'attended')
        self.attended = attributes[:'attended']
      end

      if attributes.key?(:'call_id')
        self.call_id = attributes[:'call_id']
      end

      if attributes.key?(:'cid_name')
        self.cid_name = attributes[:'cid_name']
      end

      if attributes.key?(:'cid_number')
        self.cid_number = attributes[:'cid_number']
      end

      if attributes.key?(:'cid_uri')
        self.cid_uri = attributes[:'cid_uri']
      end

      if attributes.key?(:'from_tag')
        self.from_tag = attributes[:'from_tag']
      end

      if attributes.key?(:'node')
        self.node = attributes[:'node']
      end

      if attributes.key?(:'presence_id')
        self.presence_id = attributes[:'presence_id']
      end

      if attributes.key?(:'presence_realm')
        self.presence_realm = attributes[:'presence_realm']
      end

      if attributes.key?(:'presence_type')
        self.presence_type = attributes[:'presence_type']
      end

      if attributes.key?(:'presence_user')
        self.presence_user = attributes[:'presence_user']
      end

      if attributes.key?(:'ringback_id')
        self.ringback_id = attributes[:'ringback_id']
      end

      if attributes.key?(:'slot_call_id')
        self.slot_call_id = attributes[:'slot_call_id']
      end

      if attributes.key?(:'switch_uri')
        self.switch_uri = attributes[:'switch_uri']
      end

      if attributes.key?(:'to_tag')
        self.to_tag = attributes[:'to_tag']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          attended == o.attended &&
          call_id == o.call_id &&
          cid_name == o.cid_name &&
          cid_number == o.cid_number &&
          cid_uri == o.cid_uri &&
          from_tag == o.from_tag &&
          node == o.node &&
          presence_id == o.presence_id &&
          presence_realm == o.presence_realm &&
          presence_type == o.presence_type &&
          presence_user == o.presence_user &&
          ringback_id == o.ringback_id &&
          slot_call_id == o.slot_call_id &&
          switch_uri == o.switch_uri &&
          to_tag == o.to_tag
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [attended, call_id, cid_name, cid_number, cid_uri, from_tag, node, presence_id, presence_realm, presence_type, presence_user, ringback_id, slot_call_id, switch_uri, to_tag].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
