=begin
#White Label Communications CPaas API Documentation

#A CPaaS platform API

The version of the OpenAPI document: 1.1
Contact: support@whitelabelcomm.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::AccountApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::AccountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountApi' do
    it 'should create an instance of AccountApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::AccountApi)
    end
  end

  # unit tests for v1_account_accountid_children_get
  # Get Sub Account List
  # Conveniently access the list of children accounts.
  # @param accountid Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_key start_key for pagination that was returned as next_start_key from your previous call
  # @option opts [Integer] :page_size number of records to return, range 1 to 50
  # @return [ServiceDocsAccountGetAll]
  describe 'v1_account_accountid_children_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_delete
  # Delete Account
  # Delete an account within your organization.
  # @param accountid Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsAccountGetSingle]
  describe 'v1_account_accountid_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_dnsrecord_get
  # Get Account DNS Record
  # Get the DNS record of an account from the Route 53 entry.
  # @param accountid Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsAccountGetSingle]
  describe 'v1_account_accountid_dnsrecord_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_dnsrecord_post
  # Create Account DNS Record
  # Create the DNS record of an account with the help realm in the Route 53 entry.
  # @param accountid Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsAccountGetSingle]
  describe 'v1_account_accountid_dnsrecord_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_dnsrecord_put
  # Convert Account DNS Record
  # Toggle the realm DNS record between srv and cname.
  # @param accountid Account ID, 32 alpha numeric
  # @param dnsrecord record type fields with value SRV, CNAME
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsAccountGetSingle]
  describe 'v1_account_accountid_dnsrecord_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_get
  # Get Account Details
  # This endpoint will not allow for modifying or making updates, it will only allow users to view/retrieve details.
  # @param accountid Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsAccountGetSingle]
  describe 'v1_account_accountid_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_limit_get
  # Get Account Limits
  # Check the maximum number of inbound, outbound, and two-way trunks.
  # @param accountid Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsAccountLimit]
  describe 'v1_account_accountid_limit_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_limit_put
  # Set Account Limits
  # Apply parameters to restrict access to inbound, outbound, and two-way trunks.
  # @param accountid Account ID, 32 alpha numeric
  # @param limit account fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsAccountLimit]
  describe 'v1_account_accountid_limit_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_post
  # Create Sub Account
  # Establish a sub account to enable an administrator within your organization to create accounts.
  # @param accountid Account ID, 32 alpha numeric
  # @param account account fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsAccountGetSingle]
  describe 'v1_account_accountid_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_provisioningdetails_get
  # Get Account Provisioning Details
  # Get the provisioning details of an account.
  # @param accountid Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsAccountProvisioning]
  describe 'v1_account_accountid_provisioningdetails_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_provisioningdetails_resetpw_put
  # Reset the provisioning details password.
  # Reset the existing provisioning details password and set it to a new one.
  # @param accountid Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsAccountProvisioning]
  describe 'v1_account_accountid_provisioningdetails_resetpw_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_put
  # Update Account
  # Modify pertinent account data.
  # @param accountid Account ID, 32 alpha numeric
  # @param account account fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsAccountGetSingle]
  describe 'v1_account_accountid_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_apikey_get
  # Authenticate an application or user request to get the client ID and client secret for a CPaaS account.
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsAccountAPIKey]
  describe 'v1_account_apikey_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_get
  # Get Account List
  # Retrieve a list of all CPaaS accounts that exist within your organization.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_key start_key for pagination that was returned as next_start_key from your previous call
  # @option opts [Integer] :page_size number of records to return, range 1 to 50
  # @return [ServiceDocsAccountGetAll]
  describe 'v1_account_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_post
  # Create Account
  # Create an account.
  # @param account account fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsAccountGetSingle]
  describe 'v1_account_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
