=begin
#White Label Communications CPaas API Documentation

#A CPaaS platform API

The version of the OpenAPI document: 1.1
Contact: support@whitelabelcomm.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CallQueueMembershipApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CallQueueMembershipApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CallQueueMembershipApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallQueueMembershipApi' do
    it 'should create an instance of CallQueueMembershipApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CallQueueMembershipApi)
    end
  end

  # unit tests for v1_account_account_id_queuemembership_post
  # Grant Queue Membership to User
  # Allow users to create queue memberships for recipients.
  # @param account_id Account ID, 32 alpha numeric
  # @param req_body payload fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsCallQueueMemberGetSingle]
  describe 'v1_account_account_id_queuemembership_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_account_id_queuemembership_recipient_id_disable_post
  # Disable Queue Membership
  # Deactivate queue membership for a recipient.
  # @param account_id Account ID, 32 alpha numeric
  # @param recipient_id Recipient ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceAPIResponse]
  describe 'v1_account_account_id_queuemembership_recipient_id_disable_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_account_id_queuemembership_recipient_id_enable_post
  # Enable Queue Membership
  # Activate queue membership for a recipient.
  # @param account_id Account ID, 32 alpha numeric
  # @param recipient_id Recipient ID, 32 alpha numeric
  # @param req_body payload fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceAPIResponse]
  describe 'v1_account_account_id_queuemembership_recipient_id_enable_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
