=begin
#White Label Communications CPaas API Documentation

#A CPaaS platform API

The version of the OpenAPI document: 1.1
Contact: support@whitelabelcomm.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CallParkApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CallParkApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CallParkApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallParkApi' do
    it 'should create an instance of CallParkApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CallParkApi)
    end
  end

  # unit tests for v1_account_account_id_parkedcall_get
  # Get Call Park List
  # Retrieve a list of calls parked on hold in a numbered slot.
  # @param account_id Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsParkedcallGet]
  describe 'v1_account_account_id_parkedcall_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
