=begin
#White Label Communications CPaas API Documentation

#A CPaaS platform API

The version of the OpenAPI document: 1.1
Contact: support@whitelabelcomm.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DataApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DataApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DataApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DataApi' do
    it 'should create an instance of DataApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DataApi)
    end
  end

  # unit tests for v1_account_account_id_cdr_cdr_id_get
  # Get CDR Details
  # Retrieve the details of a single CDR record from an account.
  # @param account_id Account ID, 32 alpha numeric
  # @param cdr_id CDR ID, string
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsCdrGetSingle]
  describe 'v1_account_account_id_cdr_cdr_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_account_id_cdr_get
  # Get CDR List
  # Retrieve a list of CDRs in a specific account.
  # @param account_id Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page_size Page size (Maximum number of results to display per page)
  # @option opts [String] :start_key Start key (Starting offset for displaying results)
  # @option opts [String] :created_from For displaying records which are created on or after this timestamp (Supported timestamp formats: iso 8601, unix time in seconds or milliseconds or microseconds or nanoseconds)
  # @option opts [String] :created_to For displaying records which are created on or before this timestamp (Supported timestamp formats: iso 8601, unix time in seconds or milliseconds or microseconds or nanoseconds)
  # @return [ServiceDocsCdrGetAll]
  describe 'v1_account_account_id_cdr_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_data_call_daily_summary_get
  # Get Call Daily Summary List
  # Retrieve a daily summary of calls, including the account ID that made or received a call, the call type, the month and year, the duration, and other relevant information.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id 
  # @option opts [String] :call_type 
  # @option opts [String] :end_date 
  # @option opts [Integer] :page_size 
  # @option opts [String] :start_date 
  # @option opts [String] :start_key 
  # @return [ServiceDocsCallDailySummary]
  describe 'v1_data_call_daily_summary_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_data_call_detail_get
  # Get Call Detail List
  # Retrieve specific details about a call (e.g., caller, recipient, date, time, duration, etc.).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account 
  # @option opts [String] :call_type 
  # @option opts [String] :callee_name 
  # @option opts [String] :callee_number 
  # @option opts [String] :caller_name 
  # @option opts [String] :caller_number 
  # @option opts [String] :end_date 
  # @option opts [Integer] :page_size 
  # @option opts [String] :start_date 
  # @option opts [String] :start_key 
  # @return [ServiceDocsCallDetail]
  describe 'v1_data_call_detail_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_data_call_monthly_summary_get
  # Get Call Detail List
  # Retrieve a monthly summary of calls, including which accounts made or received calls, the call type, and other relevant information.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account 
  # @option opts [String] :call_type 
  # @option opts [Integer] :end_month 
  # @option opts [Integer] :end_year 
  # @option opts [Integer] :page_size 
  # @option opts [String] :start_key 
  # @option opts [Integer] :start_month 
  # @option opts [Integer] :start_year 
  # @return [ServiceDocsCallMonthlySummary]
  describe 'v1_data_call_monthly_summary_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_data_endpoint_list_get
  # Get Endpoint List
  # Access the endpoint list for each CPaaS API.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :endpoint_name 
  # @option opts [String] :feature_name 
  # @option opts [Integer] :page_size 
  # @option opts [String] :start_key 
  # @option opts [String] :transaction_type 
  # @option opts [String] :version 
  # @return [ServiceDocsEndpointList]
  describe 'v1_data_endpoint_list_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_data_event_daily_summary_get
  # Get Event Daily Summary List
  # Obtain a daily summary of events in a CPaaS account (e.g., setting/resetting the presence status for a user or extension).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id 
  # @option opts [String] :component 
  # @option opts [String] :end_date 
  # @option opts [Integer] :page_size 
  # @option opts [String] :start_date 
  # @option opts [String] :start_key 
  # @return [ServiceDocsEventDailySummary]
  describe 'v1_data_event_daily_summary_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_data_event_detail_get
  # Get Event Details
  # Obtain specific details about an event (e.g., an E911 notification, a deleted account, or a created user).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id 
  # @option opts [String] :component 
  # @option opts [String] :end_date_time 
  # @option opts [String] :event_name 
  # @option opts [String] :exec_status 
  # @option opts [Integer] :page_size 
  # @option opts [String] :start_date_time 
  # @option opts [String] :start_key 
  # @option opts [String] :username 
  # @return [ServiceDocsEventDetail]
  describe 'v1_data_event_detail_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_data_event_monthly_summary_get
  # Get Event Monthly Summary List
  # Obtain a monthly summary of events in a CPaaS account (e.g., adding media files or assigning phone numbers).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id 
  # @option opts [String] :component 
  # @option opts [Integer] :end_month 
  # @option opts [Integer] :end_year 
  # @option opts [Integer] :page_size 
  # @option opts [String] :start_key 
  # @option opts [Integer] :start_month 
  # @option opts [Integer] :start_year 
  # @return [ServiceDocsEventMonthlySummary]
  describe 'v1_data_event_monthly_summary_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_data_feature_daily_summary_get
  # Get Feature Daily Summary List
  # Retrieve a daily summary about a feature, including usage, which accounts execute the steps, and other relevant information.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :end_date 
  # @option opts [String] :feature_name 
  # @option opts [Integer] :page_size 
  # @option opts [String] :start_date 
  # @option opts [String] :start_key 
  # @return [ServiceDocsFeatureDailySummary]
  describe 'v1_data_feature_daily_summary_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_data_feature_monthly_summary_get
  # Get Feature Monthly Summary List
  # Retrieve a monthly summary about a feature’s usage, new users, updates, and other relevant information.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :end_month 
  # @option opts [Integer] :end_year 
  # @option opts [String] :feature_name 
  # @option opts [Integer] :page_size 
  # @option opts [String] :start_key 
  # @option opts [Integer] :start_month 
  # @option opts [Integer] :start_year 
  # @return [ServiceDocsFeatureMonthlySummary]
  describe 'v1_data_feature_monthly_summary_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
