=begin
#White Label Communications CPaas API Documentation

#A CPaaS platform API

The version of the OpenAPI document: 1.1
Contact: support@whitelabelcomm.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DeviceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DeviceApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DeviceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeviceApi' do
    it 'should create an instance of DeviceApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DeviceApi)
    end
  end

  # unit tests for v1_account_accountid_device_deviceid_delete
  # Delete Device
  # Remove one device from a CPaaS account.
  # @param accountid Account ID, 32 alpha numeric
  # @param deviceid Device ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsDeviceGetSingle]
  describe 'v1_account_accountid_device_deviceid_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_device_deviceid_get
  # Get Device Details
  # Permit a user to view specific device details.
  # @param accountid Account ID, 32 alpha numeric
  # @param deviceid Device ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsDeviceGetSingle]
  describe 'v1_account_accountid_device_deviceid_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_device_deviceid_put
  # Update Device
  # Edit specifics about the device, such as the device type, name, and owner.
  # @param accountid Account ID, 32 alpha numeric
  # @param deviceid Device ID, 32 alpha numeric
  # @param device device fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsDeviceGetSingle]
  describe 'v1_account_accountid_device_deviceid_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_device_deviceid_reboot_post
  # Reboot Device
  # Reboot a device in an account to mitigate malware and improve device performance.
  # @param accountid Account ID, 32 alpha numeric
  # @param deviceid Device ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsDeviceReboot]
  describe 'v1_account_accountid_device_deviceid_reboot_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_device_get
  # Get Device List
  # Obtain a list of all devices associated with an account such as fax machines, cell phones, and soft phones.
  # @param accountid Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_key start_key for pagination that was returned as next_start_key from your previous call
  # @option opts [Integer] :page_size number of records to return, range 1 to 50
  # @return [ServiceDocsDeviceGetAll]
  describe 'v1_account_accountid_device_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_device_post
  # Create Device
  # Connect a new device to an account to enhance communication methods.
  # @param accountid Account ID, 32 alpha numeric
  # @param device device fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsDeviceGetSingle]
  describe 'v1_account_accountid_device_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_device_status_get
  # Get Device Status
  # Retrieve a device’s status (e.g., registered or not registered) in an account.
  # @param accountid Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsDeviceStatus]
  describe 'v1_account_accountid_device_status_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
