=begin
#White Label Communications CPaas API Documentation

#A CPaaS platform API

The version of the OpenAPI document: 1.1
Contact: support@whitelabelcomm.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PresenceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PresenceApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::PresenceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PresenceApi' do
    it 'should create an instance of PresenceApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PresenceApi)
    end
  end

  # unit tests for v1_account_account_id_presence_extension_put
  # Set/Reset Presence for Extension
  # Set or reset the presence status of an extension.
  # @param account_id Account ID, 32 alpha numeric
  # @param extension Extension
  # @param req_body payload fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceAPIResponse]
  describe 'v1_account_account_id_presence_extension_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_account_id_presence_get
  # Get Presence Details
  # Retrieve details of presence subscriptions in an account.
  # @param account_id Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsPresenceGet]
  describe 'v1_account_account_id_presence_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_account_id_user_user_id_presence_put
  # Set/Reset Presence for User
  # Set or reset the presence status of a user within an account.
  # @param account_id Account ID, 32 alpha numeric
  # @param user_id User ID, 32 alpha numeric
  # @param req_body payload fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceAPIResponse]
  describe 'v1_account_account_id_user_user_id_presence_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
