=begin
#White Label Communications CPaas API Documentation

#A CPaaS platform API

The version of the OpenAPI document: 1.1
Contact: support@whitelabelcomm.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SMSApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SMSApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SMSApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SMSApi' do
    it 'should create an instance of SMSApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SMSApi)
    end
  end

  # unit tests for v1_sms_account_account_id_campaign_campaign_id_import_get
  # Get details about a single imported campaign in an account.
  # @param account_id Account ID, 32 alpha numeric
  # @param campaign_id Campaign ID
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsCampaignImportOutput]
  describe 'v1_sms_account_account_id_campaign_campaign_id_import_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_sms_account_account_id_campaign_campaign_id_import_post
  # Import campaign
  # @param account_id Account ID, 32 alpha numeric
  # @param campaign_id Campaign ID
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsCampaignImportOutput]
  describe 'v1_sms_account_account_id_campaign_campaign_id_import_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_sms_account_account_id_campaign_campaign_id_phonenumber_get
  # Get telephone numbers associated with a campaign.
  # @param account_id Account ID, 32 alpha numeric
  # @param campaign_id Campaign ID
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :page_num Page number
  # @option opts [Float] :page_size Page size
  # @return [ServiceDocsCampaignPhoneNumberOutput]
  describe 'v1_sms_account_account_id_campaign_campaign_id_phonenumber_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_sms_account_account_id_campaign_campaign_id_phonenumber_put
  # Associate or dissociate telephone numbers with a campaign.
  # @param account_id Account ID, 32 alpha numeric
  # @param campaign_id Campaign ID, 32 alpha numeric
  # @param req_body payload fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsCampaignTagDetagPhonenumbersOutput]
  describe 'v1_sms_account_account_id_campaign_campaign_id_phonenumber_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_sms_account_account_id_campaign_import_get
  # Get a list of all imported campaigns in an account.
  # @param account_id Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :page_num Page number
  # @option opts [Float] :page_size Page size
  # @return [ServiceDocsCampaignImportedGetAllOutput]
  describe 'v1_sms_account_account_id_campaign_import_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
