=begin
#White Label Communications CPaas API Documentation

#A CPaaS platform API

The version of the OpenAPI document: 1.1
Contact: support@whitelabelcomm.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::StorageApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StorageApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::StorageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StorageApi' do
    it 'should create an instance of StorageApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::StorageApi)
    end
  end

  # unit tests for v1_account_account_id_storage_delete
  # Delete Storage
  # Delete items that are stored in an account.
  # @param account_id Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsStorageGet]
  describe 'v1_account_account_id_storage_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_account_id_storage_get
  # Get Storage Details
  # Retrieve storage details for an account.
  # @param account_id Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsStorageGet]
  describe 'v1_account_account_id_storage_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_account_id_storage_post
  # Create Storage
  # Create storage in an account for voicemails, call recordings, faxes, etc.
  # @param account_id Account ID, 32 alpha numeric
  # @param req_body payload fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsStorageGet]
  describe 'v1_account_account_id_storage_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_account_id_storage_put
  # Update Storage
  # Modify the names of metadata to make it easier to locate (e.g., change the name of voicemail_storage to voicemail_and_callrecordings_storage, etc.).
  # @param account_id Account ID, 32 alpha numeric
  # @param req_body payload fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsStorageGet]
  describe 'v1_account_account_id_storage_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
