=begin
#White Label Communications CPaas API Documentation

#A CPaaS platform API

The version of the OpenAPI document: 1.1
Contact: support@whitelabelcomm.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::VoIPUserApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VoIPUserApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::VoIPUserApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VoIPUserApi' do
    it 'should create an instance of VoIPUserApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::VoIPUserApi)
    end
  end

  # unit tests for v1_account_accountid_user_get
  # Get User List
  # Get a list of all VoIP users that includes first and last names, email addresses, extensions, and account statuses.
  # @param accountid Account ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_key start_key for pagination that was returned as next_start_key from your previous call
  # @option opts [Integer] :page_size number of records to return, range 1 to 50
  # @return [ServiceDocsUserGetAll]
  describe 'v1_account_accountid_user_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_user_post
  # Create User
  # Add new users to the account. When a user is added, the system generates their unique 32 alpha numeric ID.
  # @param accountid Account ID, 32 alpha numeric
  # @param user user fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsUserGetSingle]
  describe 'v1_account_accountid_user_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_user_userid_delete
  # Delete User
  # Delete VoIP user access to maintain the security of your accounts.
  # @param accountid Account ID, 32 alpha numeric
  # @param userid User ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsUserGetSingle]
  describe 'v1_account_accountid_user_userid_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_user_userid_get
  # Get User Details
  # View specific user details.
  # @param accountid Account ID, 32 alpha numeric
  # @param userid User ID, 32 alpha numeric
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsUserGetSingle]
  describe 'v1_account_accountid_user_userid_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_accountid_user_userid_put
  # Update User
  # Keep user information current. Modify the first and last name, extension, and other pertinent information.
  # @param accountid Account ID, 32 alpha numeric
  # @param userid User ID, 32 alpha numeric
  # @param user user fields
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsUserGetSingle]
  describe 'v1_account_accountid_user_userid_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
