=begin
#White Label Communications CPaas API Documentation

#A CPaaS platform API

The version of the OpenAPI document: 1.1
Contact: support@whitelabelcomm.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::WebhookApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhookApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::WebhookApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhookApi' do
    it 'should create an instance of WebhookApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::WebhookApi)
    end
  end

  # unit tests for v1_webhook_account_account_id_get
  # Get Webhook List
  # Retrieve the webhook list in an account.
  # @param account_id Account ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size number of records to return, range 1 to 50
  # @option opts [Integer] :current_page Current Page
  # @return [ServiceDocsWebhookGetAll]
  describe 'v1_webhook_account_account_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_webhook_account_account_id_post
  # Create Webhook
  # Create a webhook for a specific account ID.
  # @param account_id Account ID
  # @param body Webhook data
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsWebhookGetSingle]
  describe 'v1_webhook_account_account_id_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_webhook_account_account_id_webhook_id_delete
  # Delete Webhook
  # Remove a webhook identified by its ID for a particular account ID.
  # @param account_id Account ID
  # @param webhook_id Webhook ID
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsWebhookDelete]
  describe 'v1_webhook_account_account_id_webhook_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_webhook_account_account_id_webhook_id_get
  # Get Webhook Details
  # Access details about a single webhook ID for an individual account ID.
  # @param account_id Account ID
  # @param webhook_id Webhook ID
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsWebhookGetSingle]
  describe 'v1_webhook_account_account_id_webhook_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_webhook_account_account_id_webhook_id_put
  # Update Webhook
  # Update a webhook identified by its ID for a distinct account ID.
  # @param account_id Account ID
  # @param webhook_id Webhook ID
  # @param body Updated webhook data
  # @param [Hash] opts the optional parameters
  # @return [ServiceDocsWebhookGetSingle]
  describe 'v1_webhook_account_account_id_webhook_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
