=begin
#White Label Communications CPaas API Documentation

#A CPaaS platform API

The version of the OpenAPI document: 1.1
Contact: support@whitelabelcomm.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ModelsDeviceOutputFullSIP
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ModelsDeviceOutputFullSIP do
  let(:instance) { OpenapiClient::ModelsDeviceOutputFullSIP.new }

  describe 'test an instance of ModelsDeviceOutputFullSIP' do
    it 'should create an instance of ModelsDeviceOutputFullSIP' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ModelsDeviceOutputFullSIP)
    end
  end

  describe 'test attribute "invite_format"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "password"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "username"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
