=begin
#White Label Communications CPaas API Documentation

#A CPaaS platform API

The version of the OpenAPI document: 1.1
Contact: support@whitelabelcomm.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ServiceVOIPVoicemailMessageChange
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ServiceVOIPVoicemailMessageChange do
  let(:instance) { OpenapiClient::ServiceVOIPVoicemailMessageChange.new }

  describe 'test an instance of ServiceVOIPVoicemailMessageChange' do
    it 'should create an instance of ServiceVOIPVoicemailMessageChange' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ServiceVOIPVoicemailMessageChange)
    end
  end

  describe 'test attribute "folder"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["deleted", "saved", "new"])
      # validator.allowable_values.each do |value|
      #   expect { instance.folder = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "source_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
