=begin
#White Label Communications CPaas API Documentation

#A CPaaS platform API

The version of the OpenAPI document: 1.1
Contact: support@whitelabelcomm.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ServiceCallflowAddEditFlowData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ServiceCallflowAddEditFlowData do
  let(:instance) { OpenapiClient::ServiceCallflowAddEditFlowData.new }

  describe 'test an instance of ServiceCallflowAddEditFlowData' do
    it 'should create an instance of ServiceCallflowAddEditFlowData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ServiceCallflowAddEditFlowData)
    end
  end

  describe 'test attribute "children"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "_module"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["device", "offnet", "menu", "play", "temporal_route", "voicemail", "user", "call_forward", "group", "ring_group", "do_not_disturb", "park", "group_pickup", "group_pickup_feature", "intercom", "page_group", "record_call", "record_caller", "qubicle", "missed_call_alert"])
      # validator.allowable_values.each do |value|
      #   expect { instance._module = value }.not_to raise_error
      # end
    end
  end

end
